### ISSUE TITLE
Z3 Type

### ISSUE THREAD

**Issue by acmLL** [a16z/halmos#19]
I have typed: halmos, and got this

Running 1 tests for test/Vault.t.sol:SLUSDTest
Traceback (most recent call last):
  File "/usr/local/bin/halmos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/halmos/__main__.py", line 391, in main
    exitcode = run(hexcode, abi, srcmap, srcs, funname, funsig, funselector, arrlen, args, options)
  File "/usr/local/lib/python3.10/site-packages/halmos/__main__.py", line 206, in run
    gen_model(args, models, idx, ex)
  File "/usr/local/lib/python3.10/site-packages/halmos/__main__.py", line 273, in gen_model
    sol3.from_string(query)
  File "/usr/local/lib/python3.10/site-packages/z3/z3.py", line 7214, in from_string
    Z3_solver_from_string(self.ctx.ref(), self.solver, s)
  File "/usr/local/lib/python3.10/site-packages/z3/z3core.py", line 3974, in Z3_solver_from_string
    _elems.Check(a0)
  File "/usr/local/lib/python3.10/site-packages/z3/z3core.py", line 1482, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: b'(error "line 250 column 75: unknown constant evm_div ((_ BitVec 256) (_ BitVec 256)) ")\n'

**Comment by daejunpark** [comment]
@acmLL Would you mind sharing your tests to reproduce this error?

**Comment by daejunpark** [comment]
Thanks for reporting @acmLL!  It should be fixed in the latest version. Please feel free to reopen if not!
