### ISSUE TITLE
Running with python3.8 results in error

### ISSUE THREAD

**Issue by hjorthjort** [a16z/halmos#20]
The following error, specifically:
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/hjort/.local/bin/halmos", line 8, in <module>
    sys.exit(main())
  File "/home/hjort/.local/lib/python3.8/site-packages/halmos/__main__.py", line 316, in main
    args = parse_args()
  File "/home/hjort/.local/lib/python3.8/site-packages/halmos/__main__.py", line 31, in parse_args
    parser.add_argument('--use-srcmap', action=argparse.BooleanOptionalAction, default=True, help='use source mappings')
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'
```

It seems at least python3.9 should be required, based on this:
 https://nono.ma/attributeerror-module-argparse-has-no-attribute-booleanoptionalaction

**Comment by daejunpark** [comment]
Thanks for reporting, @hjorthjort! It should be fixed in the latest version. Please feel free to reopen if not!
