### ISSUE TITLE
TypeError: object of type 'BitVecRef' has no len() in padded_slice

### ISSUE THREAD

**Issue by karmacoma-eth** [a16z/halmos#269]
Repro with:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.15;

import "forge-std/Test.sol";
import {SymTest} from "halmos-cheatcodes/SymTest.sol";
import {console2} from "forge-std/console2.sol";

contract WithImmutable {
    address immutable target;

    constructor(address _target) {
        target = _target;
        console2.log("address(withImmutable).code (in constructor)");
        dumpcode();
    }

    function isTarget(address other) external returns (bool) {
        // console2.log("address(withImmutable).code (in isTarget)");
        // dumpcode();
        return other == target;
    }

    function dumpcode() internal {
        uint256 codelength;
        assembly {
            codelength := codesize()
        }

        bytes memory code = new bytes(codelength);
        assembly {
            codecopy(add(code, 0x20), 0, codesize())
        }
        console2.logBytes(code);
    }
}

contract Test71 is Test, SymTest {
    WithImmutable withImmutable;

    function setUp() public {
        address x = svm.createAddress("x");
        withImmutable = new WithImmutable(x);
        // console2.log("type(WithImmutable).creationCode");
        // console2.logBytes(type(WithImmutable).creationCode);
    }

    function test_withConcreteImmutable() external {
        assert(!withImmutable.isTarget(address(0)));
    }

    // counterexample expected
    function test_symbolicImmutable(address y) external {
        assert(!withImmutable.isTarget(y));
    }
}
```

Results in:

```
Running 1 tests for test/71_symbolicImmutable.t.sol:Test71
[console.log] address(withImmutable).code (in constructor)
Error: setUp() failed: TypeError: object of type 'BitVecRef' has no len()
Traceback (most recent call last):
  File "/Users/karma/projects/halmos/src/halmos/__main__.py", line 957, in run_sequential
    setup_ex = setup(
               ^^^^^^
  File "/Users/karma/projects/halmos/src/halmos/__main__.py", line 463, in setup
    for idx, setup_ex in enumerate(setup_exs_all):
  File "/Users/karma/projects/halmos/src/halmos/sevm.py", line 2515, in run
    data = padded_slice(calldata, offset, size, con(0, 8))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karma/projects/halmos/src/halmos/sevm.py", line 125, in padded_slice
    n = len(lst)
        ^^^^^^^^
TypeError: object of type 'BitVecRef' has no len()
Symbolic test result: 0 passed; 1 failed; time: 0.31s
```

**Comment by karmacoma-eth** [comment]
overall impression is that we really need to use a better abstraction for sequences of bytes:

- in calldata
- in returndata
- in memory

when purely concrete, we try to prefer just `bytes()`. But in some places we still expect a list of values, and other times (like in this case) just a `BitVecRef` that is a `Concat` of some large concrete buffer plus some symbolic value.

We know that lowering bitvecs to a list of extract() and concatenating them again is inefficient, need a better way.

Note that `byte_length` sounds like a good candidate to replace `len(lst)` here, but it only supports bitvecs and `bytes`, not lists 🤪

**Comment by karmacoma-eth** [comment]
fixed with chunk-based memory https://github.com/a16z/halmos/pull/288
