### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by karmacoma-eth** [a16z/halmos#273]
**Describe the bug**

On python 3.12.2:

```
Run pip install halmos
Collecting halmos
  Downloading halmos-0.1.11-py3-none-any.whl.metadata (3.1 kB)
Collecting z3-solver==4.12.2.0 (from halmos)
  Downloading z3_solver-4.12.2.0-py2.py3-none-manylinux2014_x86_64.whl.metadata (697 bytes)
Downloading halmos-0.1.11-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 4.0 MB/s eta 0:00:00
Downloading z3_solver-4.12.2.0-py2.py3-none-manylinux2014_x86_64.whl (55.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.7/55.7 MB 21.7 MB/s eta 0:00:00
Installing collected packages: z3-solver, halmos
Successfully installed halmos-0.1.11 z3-solver-4.12.2.0
```

Running halmos then fails with:

```
 Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.2/x64/bin/halmos", line 5, in <module>
    from halmos.__main__ import main
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/halmos/__main__.py", line 21, in <module>
    from .sevm import *
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/halmos/sevm.py", line 23, in <module>
    from z3 import *
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/z3/__init__.py", line 1, in <module>
    from .z3 import *
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/z3/z3.py", line 46, in <module>
    from . import z3core
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/z3/z3core.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by karmacoma-eth** [comment]
The problem is that z3-solver-4.12.2.0 imports `pkg_resources` (coming from setuptools), but declaring setuptools as a build dependency only and not a runtime dependency.

Setuptools used to be packaged with standard python distributions (so this used to work), but that's no longer the case in python 3.12.

**Comment by karmacoma-eth** [comment]
I think the fix is either to:
- unpin z3-solver to >=4.13 (which uses the builtin importlib_resources)
- keep z3-solver pinned (why?) and specify that we need setuptools as a runtime dependency

**Comment by danilych** [comment]
@karmacoma-eth  Try to install halmos via pip instead of pipx, works for me.

**Comment by karmacoma-eth** [comment]
@danilych you mean installing it globally instead of in an isolated virtualenv?

**Comment by karmacoma-eth** [comment]
confirmed that running `pip install --upgrade z3-solver` yields the following:

```sh
$ pip list                                                                                                                                                                                                                                        

Package   Version
--------- --------
halmos    0.1.11
pip       24.0
z3-solver 4.13.0.0
```

and running `python3.12 -m halmos` no longer fails with the pkg_resources error, I think it's safe to unpin
