### ISSUE TITLE
failed to run halmos in windows

### ISSUE THREAD

**Issue by rayeaster** [a16z/halmos#52]
@daejunpark Hello ser, would you please shed a light how to solve this issue? Really appreciate!

**Describe the bug**
I clone the repo and install halmos but it complained about the path

**To Reproduce**
run halmos

**Environment:**
 - OS: [Windows]
 - Python version: [3.9.7]
 - Halmos and other dependency versions: [0.0.7]

**Additional context**
it complain about the directory path as following:
```
(base) c:\xxx\code\halmos-example>halmos
Traceback (most recent call last):
  File "c:\xxx\Anaconda3-2021-11\lib\site-packages\halmos\__main__.py", line 532, in main
    cryticCompile = CryticCompile(**vars(args))
  File "c:\xxx\Anaconda3-2021-11\lib\site-packages\crytic_compile\crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "c:\xxx\Anaconda3-2021-11\lib\site-packages\crytic_compile\crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "c:\xxx\Anaconda3-2021-11\lib\site-packages\crytic_compile\platform\solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "c:\xxx\Anaconda3-2021-11\lib\site-packages\crytic_compile\platform\solc.py", line 283, in _get_targets_json
    return _run_solc(
  File "c:\xxx\Anaconda3-2021-11\lib\site-packages\crytic_compile\platform\solc.py", line 483, in _run_solc
    raise InvalidCompilation(f"{filename} does not exist (are you in the correct directory?)")
crytic_compile.platform.exceptions.InvalidCompilation: c:\xxx\code\halmos-example does not exist (are you in the correct directory?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\xxx\Anaconda3-2021-11\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\xxx\Anaconda3-2021-11\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\xxx\Anaconda3-2021-11\Scripts\halmos.exe\__main__.py", line 7, in <module>
  File "c:\xxx\Anaconda3-2021-11\lib\site-packages\halmos\__main__.py", line 534, in main
    raise ValueError('Parse error', e)
ValueError: ('Parse error', InvalidCompilation('c:\\xxx\\code\\halmos-example does not exist (are you in the correct directory?)'))
```

**Comment by tzuhancs** [comment]
Hi, I am trying to run halmos and also facing the same error. Any help would be appreciated. Thanks!

**Comment by daejunpark** [comment]
@rayeaster @tzuhancs Could you please share the output of running `forge test` in the same directory where you ran `halmos`?

**Comment by tzuhancs** [comment]
tzuhan@tzuhan:~/halmos/examples/src$ forge test
Traceback (most recent call last):
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pytest_django/plugin.py", line 179, in _handle_import_error
    yield
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pytest_django/plugin.py", line 351, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/home/tzuhan/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 189, in console_main
    code = main()
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 147, in main
    config = _prepareconfig(args, plugins)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 328, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1067, in pytest_cmdline_parse
    self.parse(args)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1354, in parse
    self._preparse(args, addopts=addopts)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1256, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pytest_django/plugin.py", line 350, in pytest_load_initial_conftests
    with _handle_import_error(_django_project_scan_outcome):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pytest_django/plugin.py", line 183, in _handle_import_error
    raise ImportError(msg)
ImportError: No module named 'settings'

pytest-django could not find a Django project (no manage.py file could be found). You must explicitly add your Django project to the Python path to have it picked up.
tzuhan@tzuhan:~/halmos/examples/src$

**Comment by tzuhancs** [comment]
I am running `forge test` and `halmos` in `~/halmos/examples/src`, is this the right place to execute halmos?

**Comment by daejunpark** [comment]
ah you should run them in `~/halmos/examples`. could you try again?

**Comment by tzuhancs** [comment]
I ran it again in `~/halmos/examples` 

tzuhan@tzuhan:~/halmos/examples$ forge test
Traceback (most recent call last):
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pytest_django/plugin.py", line 179, in _handle_import_error
    yield
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pytest_django/plugin.py", line 351, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/home/tzuhan/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 189, in console_main
    code = main()
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 147, in main
    config = _prepareconfig(args, plugins)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 328, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1067, in pytest_cmdline_parse
    self.parse(args)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1354, in parse
    self._preparse(args, addopts=addopts)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1256, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pytest_django/plugin.py", line 350, in pytest_load_initial_conftests
    with _handle_import_error(_django_project_scan_outcome):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/pytest_django/plugin.py", line 183, in _handle_import_error
    raise ImportError(msg)
ImportError: No module named 'settings'

pytest-django could not find a Django project (no manage.py file could be found). You must explicitly add your Django project to the Python path to have it picked up.

**Comment by daejunpark** [comment]
oh, i meant `forge` from Foundry: https://book.getfoundry.sh/getting-started/installation

could you please install Foundry and try again?

**Comment by tzuhancs** [comment]
`forge test` works great now! thank you. However, when I do `halmos`, it still shows the same error: 

`tzuhan@tzuhan:~/halmos/examples$ halmos
Traceback (most recent call last):
  File "/home/tzuhan/.local/lib/python3.10/site-packages/halmos/__main__.py", line 564, in main
    cryticCompile = CryticCompile(**vars(args))
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 153, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 275, in _get_targets_json
    return _run_solc(
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 463, in _run_solc
    raise InvalidCompilation(
crytic_compile.platform.exceptions.InvalidCompilation: /home/tzuhan/halmos/examples does not exist (are you in the correct directory?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tzuhan/.local/bin/halmos", line 8, in <module>
    sys.exit(main())
  File "/home/tzuhan/.local/lib/python3.10/site-packages/halmos/__main__.py", line 566, in main
    raise ValueError('Parse error', e)
ValueError: ('Parse error', InvalidCompilation('/home/tzuhan/halmos/examples does not exist (are you in the correct directory?)'))`

**Comment by karmacoma-eth** [comment]
it looks like crytic-compile is not properly detecting that this should be a forge build and so it falls back to solc, can you try running this instead?

```halmos --compile-force-framework forge```

**Comment by tzuhancs** [comment]
It is showing the same error: 

tzuhan@tzuhan:~/halmos/examples$ halmos --compile-force-framework foundry
Traceback (most recent call last):
  File "/home/tzuhan/.local/lib/python3.10/site-packages/halmos/__main__.py", line 564, in main
    cryticCompile = CryticCompile(**vars(args))
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 153, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 275, in _get_targets_json
    return _run_solc(
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 463, in _run_solc
    raise InvalidCompilation(
crytic_compile.platform.exceptions.InvalidCompilation: /home/tzuhan/halmos/examples does not exist (are you in the correct directory?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tzuhan/.local/bin/halmos", line 8, in <module>
    sys.exit(main())
  File "/home/tzuhan/.local/lib/python3.10/site-packages/halmos/__main__.py", line 566, in main
    raise ValueError('Parse error', e)
ValueError: ('Parse error', InvalidCompilation('/home/tzuhan/halmos/examples does not exist (are you in the correct directory?)'))

**Comment by daejunpark** [comment]
@tzuhancs Thanks for reporting. I think I have to setup a Windows environment to debug this issue.

In the meantime, could you please try the following and share the result with us?

```
crytic-compile .
```

Halmos uses the `crytic-compile` library to parse the source files, and the error came from the library. I'd like to see whether it originated from crytic-compile itself, or from our integration with it.

**Comment by tzuhancs** [comment]
Thank you so much @daejunpark  I just ran it and below is the result: 

tzuhan@tzuhan:~/halmos/examples$ crytic-compile .
INFO:CryticCompile:'forge clean' running (wd: /home/tzuhan/halmos/examples)
INFO:CryticCompile:'forge build --build-info --force' running
INFO:CryticCompile:Compiling 2 files with 0.8.20
Solc 0.8.20 finished in 60.36ms
Compiler run successful!

tzuhan@tzuhan:~/halmos/examples$ halmos
Traceback (most recent call last):
  File "/home/tzuhan/.local/lib/python3.10/site-packages/halmos/__main__.py", line 564, in main
    cryticCompile = CryticCompile(**vars(args))
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 153, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 275, in _get_targets_json
    return _run_solc(
  File "/home/tzuhan/.local/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 463, in _run_solc
    raise InvalidCompilation(
crytic_compile.platform.exceptions.InvalidCompilation: /home/tzuhan/halmos/examples does not exist (are you in the correct directory?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tzuhan/.local/bin/halmos", line 8, in <module>
    sys.exit(main())
  File "/home/tzuhan/.local/lib/python3.10/site-packages/halmos/__main__.py", line 566, in main
    raise ValueError('Parse error', e)
ValueError: ('Parse error', InvalidCompilation('/home/tzuhan/halmos/examples does not exist (are you in the correct directory?)'))

**Comment by daejunpark** [comment]
thanks, there seems to be an issue with our integration to the library. will look into it.

**Comment by tzuhancs** [comment]
Thank you @daejunpark , looking forward to get this fix and start using Halmos.:)!

**Comment by daejunpark** [comment]
could you please provide more info about your dev environment? like windows version, linux setup, python setup, etc.?

**Comment by tzuhancs** [comment]
OS
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


- Python 3.10.6
- solc, the solidity compiler commandline interface Version: 0.8.0+commit.c7dfd78e.Linux.g++
- foundryup: installed - forge 0.2.0 (cc5637a 2023-06-02T00:09:46.708013335Z)
- crytic-compile 0.2.2

**Comment by daejunpark** [comment]
are you running linux or windows?  or, are you running ubuntu on WSL?

**Comment by tzuhancs** [comment]
ubuntu on WSL

**Comment by tzuhancs** [comment]
@daejunpark  I just update crytic-compile to 0.3.1 and it works now!:D

tzuhan@tzuhan:~/halmos/examples$ halmos

Running 6 tests for test/Example.t.sol:ExampleTest
[PASS] testIsPowerOfTwo(uint256) (paths: 4/5, time: 23.08s, bounds: [])
[PASS] testIsPowerOfTwo(uint8) (paths: 9/11, time: 0.13s, bounds: [])
[PASS] testIsPowerOfTwoEq(uint256) (paths: 4/5, time: 0.06s, bounds: [])
[FAIL] testTotalPriceBuggy(uint96,uint32) (paths: 2/6, time: 0.16s, bounds: [])
Counterexample: [p_price_uint96 = 35898065829157585425095454745, p_quantity_uint32 = 2147614976]
[FAIL] testTotalPriceFixed(uint96,uint32) (paths: 2/6, time: 2.05s, bounds: [])
Counterexample: unknown
[PASS] testTotalPriceFixedEqualsToConservative(uint96,uint32) (paths: 1/4, time: 0.02s, bounds: [])
Symbolic test result: 4 passed; 2 failed
tzuhan@tzuhan:~/halmos/examples$ crytic-compile --version
0.3.1

**Comment by daejunpark** [comment]
ah, right, `crytic-compile >= 0.3.0` is required. not sure why it wasn't enforced by pip install. thanks for letting me know!

**Comment by daejunpark** [comment]
@rayeaster could you please check if your issue can be also fixed by upgrading crytic-compile to >=0.3.0?

**Comment by rayeaster** [comment]
@daejunpark thank you ser. It seems to work for me now under the folder `/examples` with `crytic-compile = 0.3.0` :)

**Comment by daejunpark** [comment]
@rayeaster thanks for confirming. FYI, crytic-compile is no longer needed for Halmos versions >= 0.1.0.
